include: package:lint/strict.yaml

analyzer:
  exclude:
    - '**.g.dart'
  plugins:
    - custom_lint

linter:
  rules:
    - always_put_control_body_on_new_line
    - curly_braces_in_flow_control_structures