include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.g.dart'
  plugins:
    - custom_lint
  language:
    strict-inference: true # Force to specify generic types

linter:
  rules:
    - public_member_api_docs
    - prefer_relative_imports
    - prefer_expression_function_bodies
    - always_put_control_body_on_new_line
    - curly_braces_in_flow_control_structures