format: true
use-escaping: true
nullable-getter: false
synthetic-package: false

arb-dir: lib/l10n/translations
template-arb-file: app_en.arb

output-dir: lib/l10n/app_localizations
output-localization-file: app_localizations.g.dart

untranslated-messages-file: lib/l10n/untranslated.txt