format: true
use-escaping: true
synthetic-package: false

arb-dir: lib/l10n
template-arb-file: app_en.arb

output-dir: lib/l10n/app_localizations
output-localization-file: app_localizations.g.dart

untranslated-messages-file: lib/l10n/untranslated.txt